import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div>
      <div className="w-[100%] bg-white">
        <Image
            src="/abc-logo.png"
            width={153}
            height={81}
            className="block ml-[14px]"
            alt="abc health logo"
        />
      </div>


      {children}

    </div>
    </body>
    </html>
);
}
